#!/bin/bash

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export XTY_PROJECT_ROOT="${XTY_PROJECT_ROOT:-$ROOT_DIR}"
export XTY_RUNTIME_ROOT="${XTY_RUNTIME_ROOT:-$XTY_PROJECT_ROOT/.runtime}"

export XTY_MINIO_ROOT="${XTY_MINIO_ROOT:-$XTY_RUNTIME_ROOT/minio}"
export XTY_MINIO_BIN_DIR="${XTY_MINIO_BIN_DIR:-$XTY_MINIO_ROOT/bin}"
export XTY_MINIO_DATA_DIR="${XTY_MINIO_DATA_DIR:-$XTY_MINIO_ROOT/data}"
export XTY_MINIO_CONFIG_DIR="${XTY_MINIO_CONFIG_DIR:-$XTY_MINIO_ROOT/config}"

export XTY_MILVUS_ROOT="${XTY_MILVUS_ROOT:-$XTY_RUNTIME_ROOT/milvus}"
export XTY_MILVUS_DATA_DIR="${XTY_MILVUS_DATA_DIR:-$XTY_MILVUS_ROOT/data}"
export XTY_MILVUS_LOG_FILE="${XTY_MILVUS_LOG_FILE:-$XTY_MILVUS_ROOT/milvus_server.log}"

export XTY_CONDA_ENV_NAME="${XTY_CONDA_ENV_NAME:-xtyAgent}"
