from __future__ import annotations

from typing import Any, Dict, List, Optional

from ..domain_modules.declaration_module import DeclarationGraphBuilderMixin
from ..domain_modules.finance_module import FinanceGraphBuilderMixin
from ..domain_modules.hr_module import HrGraphBuilderMixin
from ..domain_modules.project_module import ProjectGraphBuilderMixin
from ..domain_modules.risk_module import RiskGraphBuilderMixin
from ..models.graph_models import CurrentUser, GraphNode, NodeDetail


class GraphTreeBuilder(
    HrGraphBuilderMixin,
    FinanceGraphBuilderMixin,
    ProjectGraphBuilderMixin,
    DeclarationGraphBuilderMixin,
    RiskGraphBuilderMixin,
):

        def build_placeholder_tree(self, user: CurrentUser) -> GraphNode:
            return GraphNode(
                id=user.enterprise_id,
                name=user.enterprise_name,
                type='enterprise',
                category='company',
                level=0,
                side='center',
                fixed=False,
                leaf=False,
                expandable=True,
                identity_key=f'enterprise:{user.enterprise_id}',
                summary='SQL 已接通，但当前数据库中的图谱节点查询尚未补齐。',
                detail=NodeDetail(
                    basic={'企业名称': user.enterprise_name, '当前用户': user.username},
                    dynamic={'状态': '待补充真实 SQL'},
                    metrics={'说明': '请继续扩展图谱节点查询逻辑'},
                    description='当前占位树仅保留系统骨架，方便后续继续在 SQL 基础上扩展。',
                ),
                children=[],
            )

        def _detail(
            self,
            basic: Optional[Dict[str, Any]] = None,
            dynamic: Optional[Dict[str, Any]] = None,
            metrics: Optional[Dict[str, Any]] = None,
            description: str = '',
        ) -> NodeDetail:
            return NodeDetail(
                basic=basic or {},
                dynamic=dynamic or {},
                metrics=metrics or {},
                description=description,
            )

        def _node(
            self,
            *,
            node_id: str,
            name: str,
            node_type: str,
            category: str,
            level: int,
            side: str,
            parent_id: Optional[str],
            identity_key: str,
            summary: str,
            detail: Optional[NodeDetail] = None,
            fixed: bool = False,
            children: Optional[List[GraphNode]] = None,
            expandable: Optional[bool] = None,
            leaf: Optional[bool] = None,
        ) -> GraphNode:
            actual_children = children or []
            is_leaf = (not actual_children) if leaf is None else leaf
            is_expandable = bool(actual_children) if expandable is None else expandable
            return GraphNode(
                id=node_id,
                name=name,
                type=node_type,
                category=category,
                level=level,
                side=side,
                parent_id=parent_id,
                identity_key=identity_key,
                fixed=fixed,
                leaf=is_leaf,
                expandable=is_expandable,
                summary=summary,
                detail=detail or self._detail(),
                children=actual_children,
            )

        def _fixed_leaf(self, *, node_id: str, name: str, parent_id: str, side: str = 'left') -> GraphNode:
            return self._node(
                node_id=node_id,
                name=name,
                node_type=node_id,
                category='fixed_domain',
                level=2,
                side=side,
                parent_id=parent_id,
                identity_key=f'domain:{name}',
                fixed=True,
                summary='固定',
                detail=self._detail(basic={'节点层级': '二级节点'}),
                children=[],
                expandable=True,
                leaf=False,
            )

        def build_graph_tree(self, user: CurrentUser, payload: Dict[str, Any]) -> GraphNode:
            hr_payload = payload.get('hr', {})
            project_payload = payload.get('project_library', {})
            finance_payload = payload.get('finance', {})
            declaration_payload = payload.get('declaration', {})
            risk_payload = payload.get('risks', {})

            member_children = self.build_department_nodes(user.user_id, hr_payload.get('departments', []))
            wage_children = self.build_wage_staff_nodes(user.user_id, hr_payload.get('wage_staff_rows', []))
            attendance_children = self.build_attendance_group_nodes(user.user_id, hr_payload.get('attendance_groups', []))
            project_children = self.build_project_nodes(user.user_id, project_payload.get('projects', []))
            finance_fixed_asset_children = self.build_finance_fixed_asset_nodes(finance_payload.get('fixed_assets', {}).get('assets', []))
            finance_intangible_asset_children = self.build_finance_intangible_asset_nodes(finance_payload.get('intangible_assets', {}).get('assets', []))
            finance_material_children = self.build_finance_material_nodes(finance_payload.get('material_management', {}).get('materials', []))
            finance_fuel_children = self.build_finance_fuel_nodes(finance_payload.get('material_management', {}).get('fuels', []))
            finance_material_management_children = finance_material_children + finance_fuel_children

            declaration_report_files = declaration_payload.get('declaration_files', {})
            backup_files = declaration_payload.get('backup_files', {})
            declaration_additional_files = self.build_declaration_file_nodes(
                '3_ADDITIONAL_DEDUCTION_REPORTS',
                'DECLARATION_ADDITIONAL_FILE',
                declaration_report_files.get('additional_deduction_files', []) or [],
            )
            declaration_hightech_files = self.build_declaration_file_nodes(
                '3_HIGH_TECH_REPORTS',
                'DECLARATION_HIGHTECH_FILE',
                declaration_report_files.get('high_tech_files', []) or [],
            )
            declaration_enterprise_upload_files = self.build_declaration_file_nodes(
                '3_ENTERPRISE_FILE_UPLOAD',
                'DECLARATION_ENTERPRISE_UPLOAD_FILE',
                backup_files.get('enterprise_upload_files', []) or [],
            )
            declaration_system_generated_files = self.build_declaration_file_nodes(
                '3_SYSTEM_GENERATED_FILES',
                'DECLARATION_SYSTEM_GENERATED_FILE',
                backup_files.get('system_generated_files', []) or [],
            )

            risk_items_rd = self.build_risk_item_nodes('RD_RISKS', '研发风险', risk_payload.get('rd_risks', {}).get('items', []))
            risk_items_hr = self.build_risk_item_nodes('HR_RISKS', '人事风险', risk_payload.get('hr_risks', {}).get('items', []))
            risk_items_fin = self.build_risk_item_nodes('FINANCIAL_RISKS', '财务风险', risk_payload.get('financial_risks', {}).get('items', []))

            risk_summary = risk_payload.get('summary') or f"本年总风险点：{risk_payload.get('detail', {}).get('本年隐藏风险点数量', 0)}个"
            rd_summary = risk_payload.get('rd_risks', {}).get('summary') or f"本年研发风险：{risk_payload.get('rd_risks', {}).get('count', 0)}个"
            hr_summary = risk_payload.get('hr_risks', {}).get('summary') or f"本年人事风险：{risk_payload.get('hr_risks', {}).get('count', 0)}个"
            financial_summary = risk_payload.get('financial_risks', {}).get('summary') or f"本年财务风险：{risk_payload.get('financial_risks', {}).get('count', 0)}个"

            return self._node(
                node_id=user.enterprise_id,
                name=user.enterprise_name,
                node_type='ENTERPRISE',
                category='fixed_domain',
                level=0,
                side='center',
                parent_id=None,
                identity_key=f'ENTERPRISE:{user.enterprise_id}',
                fixed=False,
                summary='企业名称',
                detail=self._detail(
                    basic={
                        '企业名称': user.enterprise_name,
                        '法定代表人': user.username,
                    },
                    description='固定包含人事、财务、项目库、申报备查、风险点等业务域。',
                ),
                children=[
                    self._node(
                        node_id='1_HR',
                        name='人事',
                        node_type='1_HR',
                        category='fixed_domain',
                        level=1,
                        side='right',
                        parent_id=user.enterprise_id,
                        identity_key='domain:HR',
                        fixed=True,
                        summary=hr_payload.get('summary', '固定'),
                        detail=self._detail(
                            basic=hr_payload.get('detail', {}),
                            description=hr_payload.get('detail_description', '人事域总览。'),
                        ),
                        children=[
                            self._node(
                                node_id='2_MEMBER',
                                name='成员',
                                node_type='2_MEMBER',
                                category='fixed_domain',
                                level=2,
                                side='right',
                                parent_id='1_HR',
                                identity_key='domain:MEMBER',
                                fixed=True,
                                summary=f"共加载 {len(member_children)} 个部门",
                                detail=self._detail(
                                    basic=hr_payload.get('member_detail', {}),
                                    metrics={'部门数量': str(len(member_children))},
                                    description=hr_payload.get('member_description', '成员模块：部门到员工。'),
                                ),
                                children=member_children,
                                expandable=True,
                                leaf=False,
                            ),
                            self._node(
                                node_id='2_WAGE',
                                name='工资',
                                node_type='2_WAGE',
                                category='fixed_domain',
                                level=2,
                                side='right',
                                parent_id='1_HR',
                                identity_key='domain:WAGE',
                                fixed=True,
                                summary=f"员工数：{len(wage_children)}",
                                detail=self._detail(
                                    basic=hr_payload.get('wage_detail', {}),
                                    description=hr_payload.get('wage_description', '工资模块：直接挂员工工资。'),
                                ),
                                children=wage_children,
                                expandable=True,
                                leaf=False,
                            ),
                            self._node(
                                node_id='2_ATTENDANCE',
                                name='考勤',
                                node_type='2_ATTENDANCE',
                                category='fixed_domain',
                                level=2,
                                side='right',
                                parent_id='1_HR',
                                identity_key='domain:ATTENDANCE',
                                fixed=True,
                                summary=f"考勤组：{len(attendance_children)}",
                                detail=self._detail(
                                    basic=hr_payload.get('attendance_detail', {}),
                                    description=hr_payload.get('attendance_description', '考勤模块：考勤组到员工和资产。'),
                                ),
                                children=attendance_children,
                                expandable=True,
                                leaf=False,
                            ),
                        ],
                        expandable=True,
                        leaf=False,
                    ),
                    self._node(
                        node_id='1_PROJECT_LIBRARY',
                        name='项目库',
                        node_type='1_PROJECT_LIBRARY',
                        category='fixed_domain',
                        level=1,
                        side='left',
                        parent_id=user.enterprise_id,
                        identity_key='domain:PROJECT_LIBRARY',
                        fixed=True,
                        summary=f"项目数：{project_payload.get('detail', {}).get('该年中总研发项目数量', len(project_children))}",
                        detail=self._detail(
                            basic=project_payload.get('detail', {}),
                            description=project_payload.get('detail_description', '项目库总览。'),
                        ),
                        children=project_children,
                        expandable=bool(project_children),
                        leaf=not bool(project_children),
                    ),
                    self._node(
                        node_id='1_FINANCIAL',
                        name='财务',
                        node_type='1_FINANCIAL',
                        category='fixed_domain',
                        level=1,
                        side='right',
                        parent_id=user.enterprise_id,
                        identity_key='domain:FINANCIAL',
                        fixed=True,
                        summary=f"研发投入：{finance_payload.get('detail', {}).get('该年研发投入成本', 0)}",
                        detail=self._detail(basic=finance_payload.get('detail', {}), description='财务域总览。'),
                        children=[
                            self._node(
                                node_id='2_FIXED_ASSETS',
                                name='固定资产',
                                node_type='2_FIXED_ASSETS',
                                category='fixed_domain',
                                level=2,
                                side='right',
                                parent_id='1_FINANCIAL',
                                identity_key='domain:FIXED_ASSETS',
                                fixed=True,
                                summary=f"资产数：{len(finance_fixed_asset_children)}",
                                detail=self._detail(basic=finance_payload.get('fixed_assets', {}).get('detail', {})),
                                children=finance_fixed_asset_children,
                                expandable=bool(finance_fixed_asset_children),
                                leaf=not bool(finance_fixed_asset_children),
                            ),
                            self._node(
                                node_id='2_INTANGIBLE_ASSETS',
                                name='无形资产',
                                node_type='2_INTANGIBLE_ASSETS',
                                category='fixed_domain',
                                level=2,
                                side='right',
                                parent_id='1_FINANCIAL',
                                identity_key='domain:INTANGIBLE_ASSETS',
                                fixed=True,
                                summary=f"资产数：{len(finance_intangible_asset_children)}",
                                detail=self._detail(basic=finance_payload.get('intangible_assets', {}).get('detail', {})),
                                children=finance_intangible_asset_children,
                                expandable=bool(finance_intangible_asset_children),
                                leaf=not bool(finance_intangible_asset_children),
                            ),
                            self._node(
                                node_id='2_MATERIAL_CONSUMPTION',
                                name='物料管理',
                                node_type='2_MATERIAL_CONSUMPTION',
                                category='fixed_domain',
                                level=2,
                                side='right',
                                parent_id='1_FINANCIAL',
                                identity_key='domain:MATERIAL_CONSUMPTION',
                                fixed=True,
                                summary=f"材料：{len(finance_material_children)}；燃料：{len(finance_fuel_children)}",
                                detail=self._detail(basic=finance_payload.get('material_management', {}).get('detail', {})),
                                children=finance_material_management_children,
                                expandable=bool(finance_material_management_children),
                                leaf=not bool(finance_material_management_children),
                            ),
                            self._node(
                                node_id='2_POWER_MANAGEMENT',
                                name='动力管理',
                                node_type='2_POWER_MANAGEMENT',
                                category='fixed_domain',
                                level=2,
                                side='right',
                                parent_id='1_FINANCIAL',
                                identity_key='domain:POWER_MANAGEMENT',
                                fixed=True,
                                summary=f"金额：{finance_payload.get('power_management', {}).get('detail', {}).get('该年动力消耗金额', 0)}",
                                detail=self._detail(basic=finance_payload.get('power_management', {}).get('detail', {})),
                                children=[],
                                expandable=False,
                                leaf=True,
                            ),
                            self._node(
                                node_id='2_FINANCIAL_VOUCHER',
                                name='财务凭证',
                                node_type='2_FINANCIAL_VOUCHER',
                                category='fixed_domain',
                                level=2,
                                side='right',
                                parent_id='1_FINANCIAL',
                                identity_key='domain:FINANCIAL_VOUCHER',
                                fixed=True,
                                summary=f"金额：{finance_payload.get('financial_voucher', {}).get('detail', {}).get('该年凭证金额', 0)}",
                                detail=self._detail(basic=finance_payload.get('financial_voucher', {}).get('detail', {})),
                                children=[],
                                expandable=False,
                                leaf=True,
                            ),
                            self._node(
                                node_id='2_EXPENSE_MANAGEMENT',
                                name='费用管理',
                                node_type='2_EXPENSE_MANAGEMENT',
                                category='fixed_domain',
                                level=2,
                                side='right',
                                parent_id='1_FINANCIAL',
                                identity_key='domain:EXPENSE_MANAGEMENT',
                                fixed=True,
                                summary=f"研发口径：{finance_payload.get('expense_management', {}).get('detail', {}).get('研发口径总额', 0)}",
                                detail=self._detail(basic=finance_payload.get('expense_management', {}).get('detail', {})),
                                children=[],
                                expandable=False,
                                leaf=True,
                            ),
                            self._node(
                                node_id='2_INVOICE_MANAGEMENT',
                                name='发票管理',
                                node_type='2_INVOICE_MANAGEMENT',
                                category='fixed_domain',
                                level=2,
                                side='right',
                                parent_id='1_FINANCIAL',
                                identity_key='domain:INVOICE_MANAGEMENT',
                                fixed=True,
                                summary=f"总额：{finance_payload.get('invoice_management', {}).get('detail', {}).get('该年发票总额', 0)}",
                                detail=self._detail(basic=finance_payload.get('invoice_management', {}).get('detail', {})),
                                children=[],
                                expandable=False,
                                leaf=True,
                            ),
                            self._node(
                                node_id='2_SPECIAL_INCOME_MANAGEMENT',
                                name='特殊收入',
                                node_type='2_SPECIAL_INCOME_MANAGEMENT',
                                category='fixed_domain',
                                level=2,
                                side='right',
                                parent_id='1_FINANCIAL',
                                identity_key='domain:SPECIAL_INCOME_MANAGEMENT',
                                fixed=True,
                                summary=f"总额：{finance_payload.get('special_income_management', {}).get('detail', {}).get('该年特殊收入总额', 0)}",
                                detail=self._detail(basic=finance_payload.get('special_income_management', {}).get('detail', {})),
                                children=[],
                                expandable=False,
                                leaf=True,
                            ),
                        ],
                        expandable=True,
                        leaf=False,
                    ),
                    self._node(
                        node_id='1_DECLARATION',
                        name='申报备查',
                        node_type='1_DECLARATION',
                        category='fixed_domain',
                        level=1,
                        side='left',
                        parent_id=user.enterprise_id,
                        identity_key='domain:DECLARATION',
                        fixed=True,
                        summary=declaration_payload.get('summary', f"加计扣除：{declaration_payload.get('detail', {}).get('本年研发费用加计扣除总额', 0)}"),
                        detail=self._detail(
                            basic=declaration_payload.get('detail', {}),
                            dynamic=declaration_payload.get('detail_analysis', {}),
                            description=declaration_payload.get('detail_description', '申报备查总览。'),
                        ),
                        children=[
                            self._node(
                                node_id='2_DECLARATION_FILES',
                                name='申报文件',
                                node_type='2_DECLARATION_FILES',
                                category='fixed_domain',
                                level=2,
                                side='left',
                                parent_id='1_DECLARATION',
                                identity_key='domain:DECLARATION_FILES',
                                fixed=True,
                                summary=f"文件数：{declaration_payload.get('declaration_files', {}).get('detail', {}).get('本年申报文件数量', len(declaration_additional_files) + len(declaration_hightech_files))}",
                                detail=self._detail(
                                    basic=declaration_payload.get('declaration_files', {}).get('detail', {}),
                                    dynamic=declaration_payload.get('declaration_files', {}).get('detail_analysis', {}),
                                    description=declaration_payload.get('declaration_files', {}).get('detail_description', '申报文件汇总。'),
                                ),
                                children=[
                                    self._node(
                                        node_id='3_ADDITIONAL_DEDUCTION_REPORTS',
                                        name='加计扣除相关报表',
                                        node_type='3_ADDITIONAL_DEDUCTION_REPORTS',
                                        category='fixed_domain',
                                        level=3,
                                        side='left',
                                        parent_id='2_DECLARATION_FILES',
                                        identity_key='DECLARATION:ADDITIONAL_DEDUCTION_REPORTS',
                                        fixed=True,
                                        summary=f"文件数：{len(declaration_additional_files)}",
                                        detail=self._detail(
                                            basic=declaration_report_files.get('additional_deduction_detail', {}),
                                            dynamic=declaration_report_files.get('additional_deduction_analysis', {}),
                                            description=declaration_report_files.get('additional_deduction_description', '加计扣除相关报表。'),
                                        ),
                                        children=declaration_additional_files,
                                        expandable=bool(declaration_additional_files),
                                        leaf=not bool(declaration_additional_files),
                                    ),
                                    self._node(
                                        node_id='3_HIGH_TECH_REPORTS',
                                        name='高企相关报表',
                                        node_type='3_HIGH_TECH_REPORTS',
                                        category='fixed_domain',
                                        level=3,
                                        side='left',
                                        parent_id='2_DECLARATION_FILES',
                                        identity_key='DECLARATION:HIGH_TECH_REPORTS',
                                        fixed=True,
                                        summary=f"文件数：{len(declaration_hightech_files)}",
                                        detail=self._detail(
                                            basic=declaration_report_files.get('high_tech_detail', {}),
                                            dynamic=declaration_report_files.get('high_tech_analysis', {}),
                                            description=declaration_report_files.get('high_tech_description', '高企相关报表。'),
                                        ),
                                        children=declaration_hightech_files,
                                        expandable=bool(declaration_hightech_files),
                                        leaf=not bool(declaration_hightech_files),
                                    ),
                                ],
                                expandable=True,
                                leaf=False,
                            ),
                            self._node(
                                node_id='2_BACKUP_FILES',
                                name='备查文件',
                                node_type='2_BACKUP_FILES',
                                category='fixed_domain',
                                level=2,
                                side='left',
                                parent_id='1_DECLARATION',
                                identity_key='domain:BACKUP_FILES',
                                fixed=True,
                                summary=f"文件数：{declaration_payload.get('backup_files', {}).get('detail', {}).get('本年备查文件数量', len(declaration_enterprise_upload_files) + len(declaration_system_generated_files))}",
                                detail=self._detail(
                                    basic=declaration_payload.get('backup_files', {}).get('detail', {}),
                                    dynamic=declaration_payload.get('backup_files', {}).get('detail_analysis', {}),
                                    description=declaration_payload.get('backup_files', {}).get('detail_description', '备查文件汇总。'),
                                ),
                                children=[
                                    self._node(
                                        node_id='3_ENTERPRISE_FILE_UPLOAD',
                                        name='企业文件上传',
                                        node_type='3_ENTERPRISE_FILE_UPLOAD',
                                        category='fixed_domain',
                                        level=3,
                                        side='left',
                                        parent_id='2_BACKUP_FILES',
                                        identity_key='DECLARATION:ENTERPRISE_FILE_UPLOAD',
                                        fixed=True,
                                        summary=f"文件数：{len(declaration_enterprise_upload_files)}",
                                        detail=self._detail(
                                            basic=backup_files.get('enterprise_upload_detail', {}),
                                            dynamic=backup_files.get('enterprise_upload_analysis', {}),
                                            description=backup_files.get('enterprise_upload_description', '企业文件上传。'),
                                        ),
                                        children=declaration_enterprise_upload_files,
                                        expandable=bool(declaration_enterprise_upload_files),
                                        leaf=not bool(declaration_enterprise_upload_files),
                                    ),
                                    self._node(
                                        node_id='3_SYSTEM_GENERATED_FILES',
                                        name='系统生成',
                                        node_type='3_SYSTEM_GENERATED_FILES',
                                        category='fixed_domain',
                                        level=3,
                                        side='left',
                                        parent_id='2_BACKUP_FILES',
                                        identity_key='DECLARATION:SYSTEM_GENERATED_FILES',
                                        fixed=True,
                                        summary=f"文件数：{len(declaration_system_generated_files)}",
                                        detail=self._detail(
                                            basic=backup_files.get('system_generated_detail', {}),
                                            dynamic=backup_files.get('system_generated_analysis', {}),
                                            description=backup_files.get('system_generated_description', '系统生成。'),
                                        ),
                                        children=declaration_system_generated_files,
                                        expandable=bool(declaration_system_generated_files),
                                        leaf=not bool(declaration_system_generated_files),
                                    ),
                                ],
                                expandable=True,
                                leaf=False,
                            ),
                        ],
                        expandable=True,
                        leaf=False,
                    ),
                    self._node(
                        node_id='1_RISKS',
                        name='风险点',
                        node_type='1_RISKS',
                        category='fixed_domain',
                        level=1,
                        side='left',
                        parent_id=user.enterprise_id,
                        identity_key='domain:RISKS',
                        fixed=True,
                        summary=risk_summary,
                        detail=self._detail(
                            basic=risk_payload.get('detail', {}),
                            dynamic=risk_payload.get('detail_analysis', {}),
                            description=risk_payload.get('detail_description', '风险点总览。'),
                        ),
                        children=[
                            self._node(
                                node_id='2_RD_RISKS',
                                name='研发风险',
                                node_type='2_RD_RISKS',
                                category='fixed_domain',
                                level=2,
                                side='left',
                                parent_id='1_RISKS',
                                identity_key='domain:RD_RISKS',
                                fixed=True,
                                summary=rd_summary,
                                detail=self._detail(
                                    basic=risk_payload.get('rd_risks', {}).get('detail', {}),
                                    dynamic=risk_payload.get('rd_risks', {}).get('detail_analysis', {}),
                                    description=risk_payload.get('rd_risks', {}).get('detail_description', '研发风险总览。'),
                                ),
                                children=risk_items_rd,
                                expandable=bool(risk_items_rd),
                                leaf=not bool(risk_items_rd),
                            ),
                            self._node(
                                node_id='2_HR_RISKS',
                                name='人事风险',
                                node_type='2_HR_RISKS',
                                category='fixed_domain',
                                level=2,
                                side='left',
                                parent_id='1_RISKS',
                                identity_key='domain:HR_RISKS',
                                fixed=True,
                                summary=hr_summary,
                                detail=self._detail(
                                    basic=risk_payload.get('hr_risks', {}).get('detail', {}),
                                    dynamic=risk_payload.get('hr_risks', {}).get('detail_analysis', {}),
                                    description=risk_payload.get('hr_risks', {}).get('detail_description', '人事风险总览。'),
                                ),
                                children=risk_items_hr,
                                expandable=bool(risk_items_hr),
                                leaf=not bool(risk_items_hr),
                            ),
                            self._node(
                                node_id='2_FINANCIAL_RISKS',
                                name='财务风险',
                                node_type='2_FINANCIAL_RISKS',
                                category='fixed_domain',
                                level=2,
                                side='left',
                                parent_id='1_RISKS',
                                identity_key='domain:FINANCIAL_RISKS',
                                fixed=True,
                                summary=financial_summary,
                                detail=self._detail(
                                    basic=risk_payload.get('financial_risks', {}).get('detail', {}),
                                    dynamic=risk_payload.get('financial_risks', {}).get('detail_analysis', {}),
                                    description=risk_payload.get('financial_risks', {}).get('detail_description', '财务风险总览。'),
                                ),
                                children=risk_items_fin,
                                expandable=bool(risk_items_fin),
                                leaf=not bool(risk_items_fin),
                            ),
                        ],
                        expandable=True,
                        leaf=False,
                    ),
                ],
                expandable=True,
                leaf=False,
            )
