// {
//     "code": 0,
//     "msg": "成功",
//     "data": {
//         "menuInfo": [
//             {
//                 "id": 1,
//                 "enableStatus": 1,
//                 "parentId": 0, //上级编号 0为顶级菜单
//                 "name": "系统管理", //菜单名称
//                 "code": "SYSTEM_MANAGEMENT", //菜单唯一代码
//                 "apiUrl": "", //请求接口地址
//                 "pageUrl": "", //页面地址
//                 "icon": "fa fa-gear", //图标
//                 "indexSort": 1, //排序
//                 "category": 9999, //类别（1=按钮，9999=菜单）
//                 "type": 9999, //类型（1=普通菜单，9999=管理菜单）
//                 "target": "_self", //菜单打开方式(_blank=浏览器打开一个新的页面，_event=提交事件，_item=子项菜单，_self=在我的首页后面打开一个新的窗口，)
//                 "enableStatusName": null,
//                 "childMenuList": [ //子菜单集合
//                     {
//                         "id": 2,
//                         "enableStatus": 1,
//                         "parentId": 1,
//                         "name": "系统用户管理",
//                         "code": "SYSTEM_USER_MANAGEMENT",
//                         "apiUrl": "",
//                         "pageUrl": "",
//                         "icon": "fa fa-user",
//                         "indexSort": 1,
//                         "category": 9999,
//                         "type": 9999,
//                         "target": "_self",
//                         "enableStatusName": null,
//                         "childMenuList": [
//                             {
//                                 "id": 4,
//                                 "enableStatus": 1,
//                                 "parentId": 2,
//                                 "name": "系统用户列表",
//                                 "code": "SYSTEM_USER_LIST_MANAGEMENT",
//                                 "apiUrl": "/system/user/page/list",
//                                 "pageUrl": "",
//                                 "icon": "fa fa-user",
//                                 "indexSort": 1,
//                                 "category": 9999,
//                                 "type": 9999,
//                                 "target": "_self",
//                                 "enableStatusName": null,
//                                 "childMenuList": [],
//                                 "buttonList": [ //菜单按钮集合
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 4,
//                                         "name": "新增",
//                                         "code": "add",
//                                         "apiUrl": "/system/user/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 1,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 4,
//                                         "name": "编辑",
//                                         "code": "edit",
//                                         "apiUrl": "/system/user/edit",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 2,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 4,
//                                         "name": "修改密码",
//                                         "code": "password",
//                                         "apiUrl": "/system/user/password",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 3,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 4,
//                                         "name": "批量删除",
//                                         "code": "batchDel",
//                                         "apiUrl": "/system/user/batch/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 4,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 4,
//                                         "name": "删除",
//                                         "code": "del",
//                                         "apiUrl": "/system/user/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 5,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 4,
//                                         "name": "分页",
//                                         "code": "find_page_list",
//                                         "apiUrl": "/system/user/find/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 6,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 4,
//                                         "name": "查看",
//                                         "code": "view",
//                                         "apiUrl": "/system/user/get/by/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 7,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 4,
//                                         "name": "上传",
//                                         "code": "upload",
//                                         "apiUrl": "/systme/user/upload",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 8,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 4,
//                                         "name": "下载",
//                                         "code": "download",
//                                         "apiUrl": "/systme/user/download",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 9,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 4,
//                                         "name": "角色授权",
//                                         "code": "system_user_role_view",
//                                         "apiUrl": "/system/user/role/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 10,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 4,
//                                         "name": "保存",
//                                         "code": "save",
//                                         "apiUrl": "/system/user/role/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 11,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     }
//                                 ]
//                             }
//                         ]
//                     },
//                     {
//                         "id": 3,
//                         "enableStatus": 1,
//                         "parentId": 1,
//                         "name": "权限管理",
//                         "code": "SYSTEM_PERMISSION_MANAGEMENT",
//                         "apiUrl": "",
//                         "pageUrl": "",
//                         "icon": "fa fa-bars",
//                         "indexSort": 2,
//                         "category": 9999,
//                         "type": 9999,
//                         "target": "_self",
//                         "enableStatusName": null,
//                         "childMenuList": [
//                             {
//                                 "id": 5,
//                                 "enableStatus": 1,
//                                 "parentId": 3,
//                                 "name": "角色列表",
//                                 "code": "SYSTEM_ROLE_LIST_MANAGEMENT",
//                                 "apiUrl": "/system/role/page/list",
//                                 "pageUrl": "",
//                                 "icon": "fa fa-window-maximize",
//                                 "indexSort": 1,
//                                 "category": 9999,
//                                 "type": 9999,
//                                 "target": "_self",
//                                 "enableStatusName": null,
//                                 "childMenuList": [],
//                                 "buttonList": [
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 5,
//                                         "name": "新增",
//                                         "code": "add",
//                                         "apiUrl": "/system/role/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 1,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 5,
//                                         "name": "编辑",
//                                         "code": "edit",
//                                         "apiUrl": "/system/role/edit",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 2,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 5,
//                                         "name": "批量删除",
//                                         "code": "batchDel",
//                                         "apiUrl": "/system/role/batch/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 3,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 5,
//                                         "name": "删除",
//                                         "code": "del",
//                                         "apiUrl": "/system/role/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 4,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 5,
//                                         "name": "分页",
//                                         "code": "find_page_list",
//                                         "apiUrl": "/system/role/find/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 5,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 5,
//                                         "name": "查看",
//                                         "code": "view",
//                                         "apiUrl": "/system/role/get/by/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 6,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 5,
//                                         "name": "菜单授权",
//                                         "code": "system_role_menu_view",
//                                         "apiUrl": "/system/role/menu/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 11,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 5,
//                                         "name": "保存",
//                                         "code": "save",
//                                         "apiUrl": "/system/role/menu/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 12,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     }
//                                 ]
//                             },
//                             {
//                                 "id": 6,
//                                 "enableStatus": 1,
//                                 "parentId": 3,
//                                 "name": "菜单列表",
//                                 "code": "T_ENTERPRISE_MENU_LIST_MANAGEMENT",
//                                 "apiUrl": "/system/menu/page/list",
//                                 "pageUrl": "",
//                                 "icon": "fa fa-bars",
//                                 "indexSort": 2,
//                                 "category": 9999,
//                                 "type": 9999,
//                                 "target": "_self",
//                                 "enableStatusName": null,
//                                 "childMenuList": [],
//                                 "buttonList": [
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 6,
//                                         "name": "查询菜单树列表",
//                                         "code": "find_tree_menu_list",
//                                         "apiUrl": "/system/menu/find/menu/tree/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 8,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 6,
//                                         "name": "新增",
//                                         "code": "add",
//                                         "apiUrl": "/system/menu/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 1,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 6,
//                                         "name": "编辑",
//                                         "code": "edit",
//                                         "apiUrl": "/system/menu/edit",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 2,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 6,
//                                         "name": "批量删除",
//                                         "code": "batchDel",
//                                         "apiUrl": "/system/menu/batch/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 3,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 6,
//                                         "name": "删除",
//                                         "code": "del",
//                                         "apiUrl": "/system/menu/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 4,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 6,
//                                         "name": "分页",
//                                         "code": "find_page_list",
//                                         "apiUrl": "/system/menu/find/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 5,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 6,
//                                         "name": "查看",
//                                         "code": "view",
//                                         "apiUrl": "/system/menu/get/by/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 6,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 6,
//                                         "name": "查询上级信息",
//                                         "code": "get_parent_info",
//                                         "apiUrl": "/system/menu/get/by/parent/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 7,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     }
//                                 ]
//                             }
//                         ]
//                     },
//                     {
//                         "id": 7,
//                         "enableStatus": 1,
//                         "parentId": 1,
//                         "name": "系统综合管理",
//                         "code": "SYSTEM_COMPOSITE_MANAGEMENT",
//                         "apiUrl": "",
//                         "pageUrl": "",
//                         "icon": "fa fa-slideshare",
//                         "indexSort": 3,
//                         "category": 9999,
//                         "type": 9999,
//                         "target": "_self",
//                         "enableStatusName": null,
//                         "childMenuList": [
//                             {
//                                 "id": 8,
//                                 "enableStatus": 1,
//                                 "parentId": 7,
//                                 "name": "操作日志列表",
//                                 "code": "SYSTEM_LOG_LIST_MANAGEMENT",
//                                 "apiUrl": "/system/log/page/list",
//                                 "pageUrl": "",
//                                 "icon": "fa fa-file-text",
//                                 "indexSort": 1,
//                                 "category": 9999,
//                                 "type": 9999,
//                                 "target": "_self",
//                                 "enableStatusName": null,
//                                 "childMenuList": [],
//                                 "buttonList": [
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 8,
//                                         "name": "分页",
//                                         "code": "find_page_list",
//                                         "apiUrl": "/system/log/find/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 1,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 8,
//                                         "name": "查看",
//                                         "code": "view",
//                                         "apiUrl": "/system/log/get/by/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 1,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     }
//                                 ]
//                             },
//                             {
//                                 "id": 9,
//                                 "enableStatus": 1,
//                                 "parentId": 7,
//                                 "name": "类型列表",
//                                 "code": "TYPE_LIST_MANAGEMENT",
//                                 "apiUrl": "/common/type/page/list",
//                                 "pageUrl": "",
//                                 "icon": "fa fa-file-text",
//                                 "indexSort": 2,
//                                 "category": 9999,
//                                 "type": 9999,
//                                 "target": "_self",
//                                 "enableStatusName": null,
//                                 "childMenuList": [],
//                                 "buttonList": [
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "新增",
//                                         "code": "add",
//                                         "apiUrl": "/common/type/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 1,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "编辑",
//                                         "code": "edit",
//                                         "apiUrl": "/common/type/edit",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 2,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "批量删除",
//                                         "code": "batchDel",
//                                         "apiUrl": "/common/type/batch/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 3,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "删除",
//                                         "code": "del",
//                                         "apiUrl": "/common/type/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 4,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "分页",
//                                         "code": "find_page_list",
//                                         "apiUrl": "/common/type/find/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 5,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "查看",
//                                         "code": "view",
//                                         "apiUrl": "/common/type/get/by/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 6,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "子项列表",
//                                         "code": "type_item_view",
//                                         "apiUrl": "/common/type/item/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 10,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "子项新增",
//                                         "code": "itemAdd",
//                                         "apiUrl": "/common/type/item/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 11,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "子项编辑",
//                                         "code": "itemEdit",
//                                         "apiUrl": "/common/type/item/edit",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 12,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "子项批量删除",
//                                         "code": "itemBatchDel",
//                                         "apiUrl": "/common/type/item/batch/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 13,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "子项删除",
//                                         "code": "itemDel",
//                                         "apiUrl": "/common/type/item/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 14,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "子项分页",
//                                         "code": "item_find_page_list",
//                                         "apiUrl": "/common/type/item/find/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 15,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 9,
//                                         "name": "子项查看",
//                                         "code": "itemView",
//                                         "apiUrl": "/common/type/item/get/by/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 16,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     }
//                                 ]
//                             },
//                             {
//                                 "id": 10,
//                                 "enableStatus": 1,
//                                 "parentId": 7,
//                                 "name": "字典列表",
//                                 "code": "DICT_LIST_MANAGEMENT",
//                                 "apiUrl": "/common/dict/page/list",
//                                 "pageUrl": "",
//                                 "icon": "fa fa-file-text",
//                                 "indexSort": 3,
//                                 "category": 9999,
//                                 "type": 9999,
//                                 "target": "_self",
//                                 "enableStatusName": null,
//                                 "childMenuList": [],
//                                 "buttonList": [
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 10,
//                                         "name": "新增",
//                                         "code": "add",
//                                         "apiUrl": "/common/dict/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 1,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 10,
//                                         "name": "编辑",
//                                         "code": "edit",
//                                         "apiUrl": "/common/dict/edit",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 2,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 10,
//                                         "name": "批量删除",
//                                         "code": "batchDel",
//                                         "apiUrl": "/common/dict/batch/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 3,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 10,
//                                         "name": "删除",
//                                         "code": "del",
//                                         "apiUrl": "/common/dict/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 4,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 10,
//                                         "name": "分页",
//                                         "code": "find_page_list",
//                                         "apiUrl": "/common/dict/find/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 5,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 10,
//                                         "name": "查看",
//                                         "code": "view",
//                                         "apiUrl": "/common/dict/get/by/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 6,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     }
//                                 ]
//                             },
//                             {
//                                 "id": 11,
//                                 "enableStatus": 1,
//                                 "parentId": 7,
//                                 "name": "后台白名单IP列表",
//                                 "code": "SYSTEM_BACKSTAGE_WHITE_LIST_IP_MANAGEMENT",
//                                 "apiUrl": "/system/backstage/white/list/ip/page/list",
//                                 "pageUrl": "",
//                                 "icon": "fa fa-file-text",
//                                 "indexSort": 4,
//                                 "category": 9999,
//                                 "type": 9999,
//                                 "target": "_self",
//                                 "enableStatusName": null,
//                                 "childMenuList": [],
//                                 "buttonList": [
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 11,
//                                         "name": "新增",
//                                         "code": "add",
//                                         "apiUrl": "/system/backstage/white/list/ip/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 1,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 11,
//                                         "name": "编辑",
//                                         "code": "edit",
//                                         "apiUrl": "/system/backstage/white/list/ip/edit",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 2,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 11,
//                                         "name": "删除",
//                                         "code": "del",
//                                         "apiUrl": "/system/backstage/white/list/ip/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 4,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 11,
//                                         "name": "删除",
//                                         "code": "del",
//                                         "apiUrl": "/system/backstage/white/list/ip/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 4,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 11,
//                                         "name": "分页",
//                                         "code": "find_page_list",
//                                         "apiUrl": "/system/backstage/white/list/ip/find/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 5,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 11,
//                                         "name": "查看",
//                                         "code": "view",
//                                         "apiUrl": "/system/backstage/white/list/ip/get/by/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 6,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     }
//                                 ]
//                             },
//                             {
//                                 "id": 12,
//                                 "enableStatus": 1,
//                                 "parentId": 7,
//                                 "name": "后台黑名单IP列表",
//                                 "code": "SYSTEM_BACKSTAGE_BLACK_LIST_IP_MANAGEMENT",
//                                 "apiUrl": "/system/backstage/black/list/ip/page/list",
//                                 "pageUrl": "",
//                                 "icon": "fa fa-file-text",
//                                 "indexSort": 5,
//                                 "category": 9999,
//                                 "type": 9999,
//                                 "target": "_self",
//                                 "enableStatusName": null,
//                                 "childMenuList": [],
//                                 "buttonList": [
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 12,
//                                         "name": "新增",
//                                         "code": "add",
//                                         "apiUrl": "/system/backstage/black/list/ip/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 1,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 12,
//                                         "name": "编辑",
//                                         "code": "edit",
//                                         "apiUrl": "/system/backstage/black/list/ip/edit",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 2,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 12,
//                                         "name": "批量删除",
//                                         "code": "batchDel",
//                                         "apiUrl": "/system/backstage/black/list/ip/batch/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 3,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 12,
//                                         "name": "删除",
//                                         "code": "del",
//                                         "apiUrl": "/system/backstage/black/list/ip/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 4,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 12,
//                                         "name": "分页",
//                                         "code": "find_page_list",
//                                         "apiUrl": "/system/backstage/black/list/ip/find/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 5,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 12,
//                                         "name": "查看",
//                                         "code": "view",
//                                         "apiUrl": "/system/backstage/black/list/ip/get/by/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 6,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     }
//                                 ]
//                             },
//                             {
//                                 "id": 13,
//                                 "enableStatus": 1,
//                                 "parentId": 7,
//                                 "name": "前端白名单IP列表",
//                                 "code": "SYSTEM_FRONT_WHITE_LIST_IP_MANAGEMENT",
//                                 "apiUrl": "/system/front/white/list/ip/page/list",
//                                 "pageUrl": "",
//                                 "icon": "fa fa-file-text",
//                                 "indexSort": 6,
//                                 "category": 9999,
//                                 "type": 9999,
//                                 "target": "_self",
//                                 "enableStatusName": null,
//                                 "childMenuList": [],
//                                 "buttonList": [
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 13,
//                                         "name": "新增",
//                                         "code": "add",
//                                         "apiUrl": "/system/front/white/list/ip/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 1,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 13,
//                                         "name": "编辑",
//                                         "code": "edit",
//                                         "apiUrl": "/system/front/white/list/ip/edit",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 2,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 13,
//                                         "name": "批量删除",
//                                         "code": "batchDel",
//                                         "apiUrl": "/system/front/white/list/ip/batch/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 3,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 13,
//                                         "name": "删除",
//                                         "code": "del",
//                                         "apiUrl": "/system/front/white/list/ip/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 4,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 13,
//                                         "name": "分页",
//                                         "code": "find_page_list",
//                                         "apiUrl": "/system/front/white/list/ip/find/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 5,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 13,
//                                         "name": "查看",
//                                         "code": "view",
//                                         "apiUrl": "/system/front/white/list/ip/get/by/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 6,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     }
//                                 ]
//                             },
//                             {
//                                 "id": 14,
//                                 "enableStatus": 1,
//                                 "parentId": 7,
//                                 "name": "前端黑名单IP列表",
//                                 "code": "SYSTEM_FRONT_BLACK_LIST_IP_MANAGEMENT",
//                                 "apiUrl": "/system/front/black/list/ip/page/list",
//                                 "pageUrl": "",
//                                 "icon": "fa fa-file-text",
//                                 "indexSort": 7,
//                                 "category": 9999,
//                                 "type": 9999,
//                                 "target": "_self",
//                                 "enableStatusName": null,
//                                 "childMenuList": [],
//                                 "buttonList": [
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 14,
//                                         "name": "新增",
//                                         "code": "add",
//                                         "apiUrl": "/system/front/black/list/ip/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 1,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 14,
//                                         "name": "编辑",
//                                         "code": "edit",
//                                         "apiUrl": "/system/front/black/list/ip/edit",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 2,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 14,
//                                         "name": "批量删除",
//                                         "code": "batchDel",
//                                         "apiUrl": "/system/front/black/list/ip/batch/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 3,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 14,
//                                         "name": "删除",
//                                         "code": "del",
//                                         "apiUrl": "/system/front/black/list/ip/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 4,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 14,
//                                         "name": "分页",
//                                         "code": "find_page_list",
//                                         "apiUrl": "/system/front/black/list/ip/find/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 5,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 14,
//                                         "name": "查看",
//                                         "code": "view",
//                                         "apiUrl": "/system/front/black/list/ip/get/by/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 6,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     }
//                                 ]
//                             },
//                             {
//                                 "id": 15,
//                                 "enableStatus": 1,
//                                 "parentId": 7,
//                                 "name": "附件列表",
//                                 "code": "ANNEX_LIST_MANAGEMENT",
//                                 "apiUrl": "/common/annex/page/list",
//                                 "pageUrl": "",
//                                 "icon": "fa fa-file-text",
//                                 "indexSort": 8,
//                                 "category": 9999,
//                                 "type": 9999,
//                                 "target": "_self",
//                                 "enableStatusName": null,
//                                 "childMenuList": [],
//                                 "buttonList": [
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 15,
//                                         "name": "新增",
//                                         "code": "add",
//                                         "apiUrl": "/common/annex/save",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 1,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 15,
//                                         "name": "编辑",
//                                         "code": "edit",
//                                         "apiUrl": "/common/annex/edit",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 2,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 15,
//                                         "name": "批量删除",
//                                         "code": "batchDel",
//                                         "apiUrl": "/common/annex/batch/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 3,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 15,
//                                         "name": "删除",
//                                         "code": "del",
//                                         "apiUrl": "/common/annex/del",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 4,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 15,
//                                         "name": "分页",
//                                         "code": "find_page_list",
//                                         "apiUrl": "/common/annex/find/page/list",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 5,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     },
//                                     {
//                                         "enableStatus": 1,
//                                         "parentId": 15,
//                                         "name": "查看",
//                                         "code": "view",
//                                         "apiUrl": "/common/annex/get/by/id/info",
//                                         "pageUrl": "",
//                                         "icon": "1",
//                                         "indexSort": 6,
//                                         "category": 1,
//                                         "type": 9999,
//                                         "target": "_event",
//                                         "enableStatusName": null
//                                     }
//                                 ]
//                             }
//                         ]
//                     },
//                     {
//                         "id": 20,
//                         "enableStatus": 1,
//                         "parentId": 1,
//                         "name": "数据权限管理",
//                         "code": "DATA_PERMISSION_MANAGEMENT",
//                         "apiUrl": "",
//                         "pageUrl": "",
//                         "icon": "fa fa-table",
//                         "indexSort": 4,
//                         "category": 9999,
//                         "type": 9999,
//                         "target": "_self",
//                         "enableStatusName": null,
//                         "childMenuList": []
//                     }
//                 ]
//             }
//         ],
//         "homeInfo": {
//             "name": "",
//             "icon": "fa fa-home",
//             "url": "/init/home"
//         }
//     },
//     "timeStamp": 1752218294878
// }